version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "StrongPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1443:1433"
    networks:
      - mynetwork

  web:
    build: .
    container_name: mywebapp
    ports:
      - "5000:80"
    depends_on:
      - mssql
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=MyAppDb;User Id=sa;Password=1427174Ata.;"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
