// <auto-generated />
using System;
using LawFirmWebPage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LawFirmWebPage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250408172041_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LawFirmWebPage.Entities.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmet.yilmaz@example.com",
                            Message = "Merhaba, size nasıl yardımcı olabilirim?",
                            Name = "Ahmet",
                            SentDate = new DateTime(2025, 4, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Surname = "Yılmaz"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mehmet.kaya@example.com",
                            Message = "Web sitenizle ilgili birkaç sorum var.",
                            Name = "Mehmet",
                            SentDate = new DateTime(2025, 4, 8, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Surname = "Kaya"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ayse.demir@example.com",
                            Message = "Hizmetleriniz hakkında daha fazla bilgi almak istiyorum.",
                            Name = "Ayşe",
                            SentDate = new DateTime(2025, 4, 8, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Surname = "Demir"
                        },
                        new
                        {
                            Id = 4,
                            Email = "fatma.ozdemir@example.com",
                            Message = "İş birliği yapmak istiyoruz.",
                            Name = "Fatma",
                            SentDate = new DateTime(2025, 4, 8, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Surname = "Özdemir"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ali.celik@example.com",
                            Message = "Projelerinizle ilgili detayları öğrenmek istiyorum.",
                            Name = "Ali",
                            SentDate = new DateTime(2025, 4, 8, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Surname = "Çelik"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
